sudo: required

language: java
jdk: oraclejdk8

addons:
  apt:
    packages:
      - docker-ce

script: mvn clean install -B

after_success:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - export MONITORING=proshik/monitoring-server
  - export COMMIT=${TRAVIS_COMMIT::8}

# Docker
  - docker build -t $MONITORING:$COMMIT .
  - docker tag $MONITORING:$COMMIT $MONITORING:$TAG
  - docker login -u $DOCKER_USER -p $DOCKER_PASS  
  - docker push $MONITORING:$TAG
